name: test

on:
  push:
    branched:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest # action 스크립트가 작동될 OS

    steps: # 작업 단계
      - name: Checkout source code # 단계별 이름, 구분자로 소스를 가져옴
        uses: actions/checkout@v2

      # jdk setting
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'


      - name: Grant execute permission for gradlew
        working-directory: ./test
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        working-directory: ./test
        run: ./gradlew clean build
        shell: bash

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDTHHmm
          utcOffset: "+09:00"

      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp test/build/libs/test-0.0.1-SNAPSHOT.jar deploy/test-1.jar
          cp Procfile deploy/Procfile
          # cp -r .ebextensions deploy/.ebextensions
          cd deploy && zip -r test-${{steps.current-time.outputs.formattedTime}}-${{github.sha}} .

      - name: Deploy Consumer to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: test
          environment_name: Test-env-1
          version_label: #test-label-${{steps.current-time.outputs.formattedTime}}-${{github.sha}}
          region: ap-northeast-2
          deployment_package: deploy/test-label-${{steps.current-time.outputs.formattedTime}}-${{github.sha}}.zip